name: kinetic
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  firebase_core: ^4.10.0
  cloud_firestore: ^6.5.0
  firebase_auth: ^6.5.2
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # السطر ده مهم جداً عشان ملفات اللغة تتبني تلقائياً
  generate: true 

  # لما نجهز الصور والأيقونات هنشيل علامة الـ # من هنا
  assets:
    - assets/images/
    - assets/sounds/
  #   - assets/icons/

  # لما نحمل خط Inter هنشيل علامة الـ # من هنا
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-Black.ttf
  #         weight: 900