// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgD92EZTs375fhfheblqK1s57EL-UZIFY',
    appId: '1:209129331418:web:8eb8cca47bdd781c6523e3',
    messagingSenderId: '209129331418',
    projectId: 'kinetic-f46f7',
    authDomain: 'kinetic-f46f7.firebaseapp.com',
    storageBucket: 'kinetic-f46f7.firebasestorage.app',
    measurementId: 'G-0S0H028HPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi8H7oB-c5EZGHlClyy5F0A5RfM-S6OIc',
    appId: '1:209129331418:android:704774a6658eff6d6523e3',
    messagingSenderId: '209129331418',
    projectId: 'kinetic-f46f7',
    storageBucket: 'kinetic-f46f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtgLKJ1sjBeaSvYObl0dLHm_i_6crjVEc',
    appId: '1:209129331418:ios:9aa02b824c13cd076523e3',
    messagingSenderId: '209129331418',
    projectId: 'kinetic-f46f7',
    storageBucket: 'kinetic-f46f7.firebasestorage.app',
    iosBundleId: 'com.example.kinetic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtgLKJ1sjBeaSvYObl0dLHm_i_6crjVEc',
    appId: '1:209129331418:ios:9aa02b824c13cd076523e3',
    messagingSenderId: '209129331418',
    projectId: 'kinetic-f46f7',
    storageBucket: 'kinetic-f46f7.firebasestorage.app',
    iosBundleId: 'com.example.kinetic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgD92EZTs375fhfheblqK1s57EL-UZIFY',
    appId: '1:209129331418:web:a4a40ee80ef4c57b6523e3',
    messagingSenderId: '209129331418',
    projectId: 'kinetic-f46f7',
    authDomain: 'kinetic-f46f7.firebaseapp.com',
    storageBucket: 'kinetic-f46f7.firebasestorage.app',
    measurementId: 'G-FBS2PWM8YD',
  );
}
